import { useEffect, useMemo, useState } from "react";
import {
  useActionExplanationQuery,
  useActionsQuery,
  useAssessmentsQuery,
  useReviewActionMutation,
} from "../features/useCodeBlueData";
import { enrichActions, formatPriorityLabel, formatScopeLabel, formatTimestamp } from "../lib/derived";
import { useUiStore } from "../store/uiStore";
import type { ReviewDecisionType } from "../types/api";
import styles from "./ActionsPage.module.css";

function priorityClass(priority: string): string {
  if (priority === "critical" || priority === "high") {
    return styles.high;
  }
  if (priority === "medium") {
    return styles.medium;
  }
  return styles.low;
}

export function ActionsPage() {
  const actionsQuery = useActionsQuery();
  const assessmentsQuery = useAssessmentsQuery();
  const selectedActionId = useUiStore((state) => state.selectedActionId);
  const setSelectedActionId = useUiStore((state) => state.setSelectedActionId);
  const openTrace = useUiStore((state) => state.openTrace);

  const [reviewNotes, setReviewNotes] = useState("Reviewed by human operator.");
  const [message, setMessage] = useState<string | null>(null);

  const enrichedActions = useMemo(
    () => enrichActions(actionsQuery.data ?? [], assessmentsQuery.data ?? []),
    [actionsQuery.data, assessmentsQuery.data],
  );

  useEffect(() => {
    if (!selectedActionId && enrichedActions.length > 0) {
      setSelectedActionId(enrichedActions[0].action_id);
    }
  }, [enrichedActions, selectedActionId, setSelectedActionId]);

  const selectedAction =
    enrichedActions.find((action) => action.action_id === selectedActionId) ?? enrichedActions[0];

  const explanationQuery = useActionExplanationQuery(selectedAction?.action_id ?? null);
  const reviewMutation = useReviewActionMutation(selectedAction?.action_id ?? null);

  async function submitDecision(decision: ReviewDecisionType) {
    if (!selectedAction) {
      return;
    }

    setMessage(null);
    reviewMutation.mutate(
      {
        reviewer_role: selectedAction.required_reviewer_role,
        decision,
        rationale: reviewNotes.trim() || "No rationale provided.",
      },
      {
        onSuccess: () => {
          setMessage(`Action marked as ${decision}.`);
        },
        onError: (error) => {
          setMessage(error instanceof Error ? error.message : "Review submission failed.");
        },
      },
    );
  }

  return (
    <section className={styles.page}>
      <div className={styles.layout}>
        <section className={styles.panel}>
          <div className={styles.header}>
            <h2>Action Review Workspace</h2>
            <p>Reviewable operational actions generated by the current backend path.</p>
          </div>
          <div className={styles.filterRow}>
            <button type="button" className={styles.filterButton}>All</button>
            <button type="button" className={styles.filterButton}>Pending</button>
            <button type="button" className={styles.filterButton}>High priority</button>
          </div>
          <div className={styles.list}>
            {enrichedActions.length > 0 ? (
              enrichedActions.map((action) => (
                <article
                  key={action.action_id}
                  className={`${styles.actionCard} ${
                    action.action_id === selectedAction?.action_id ? styles.actionCardSelected : ""
                  }`}
                  onClick={() => setSelectedActionId(action.action_id)}
                >
                  <div className={styles.row}>
                    <div>
                      <h3>{action.action_type}</h3>
                      <p className={styles.meta}>
                        {formatScopeLabel(action.target_scope)} · {action.target_id}
                      </p>
                    </div>
                    <span className={`${styles.badge} ${priorityClass(action.derivedPriority)}`}>
                      {formatPriorityLabel(action.derivedPriority)}
                    </span>
                  </div>
                  <p className={styles.meta}>{action.rationale}</p>
                  <div className={styles.chips}>
                    <span className={styles.chip}>{action.required_reviewer_role}</span>
                    <span className={styles.chip}>{action.status}</span>
                  </div>
                </article>
              ))
            ) : (
              <article className={styles.actionCard}>
                <h3>No actions available</h3>
                <p className={styles.meta}>Run an assessment after loading events to generate actions.</p>
              </article>
            )}
          </div>
        </section>

        <section className={styles.detail}>
          {selectedAction ? (
            <>
              <div className={styles.detailHeader}>
                <h2>{selectedAction.action_type}</h2>
                <p>Governed recommendation surfaced by the backend for human review.</p>
              </div>

              <div className={styles.detailSection}>
                <p className={styles.label}>Action header</p>
                <div className={styles.detailGrid}>
                  <div className={styles.detailCard}>
                    <strong>Target</strong>
                    <span>{formatScopeLabel(selectedAction.target_scope)} · {selectedAction.target_id}</span>
                  </div>
                  <div className={styles.detailCard}>
                    <strong>Current status</strong>
                    <span>{selectedAction.status}</span>
                  </div>
                  <div className={styles.detailCard}>
                    <strong>Required reviewer</strong>
                    <span>{selectedAction.required_reviewer_role}</span>
                  </div>
                  <div className={styles.detailCard}>
                    <strong>Created at</strong>
                    <span>{formatTimestamp(selectedAction.created_at)}</span>
                  </div>
                </div>
              </div>

              <div className={styles.detailSection}>
                <p className={styles.label}>Why this was recommended</p>
                <div className={styles.detailCard}>
                  <p>{selectedAction.rationale}</p>
                  <p>
                    {explanationQuery.data?.explanation ?? "Explanation is being loaded from the backend."}
                  </p>
                </div>
              </div>

              <div className={styles.detailSection}>
                <p className={styles.label}>Knowledge and trace context</p>
                <div className={styles.chips}>
                  {selectedAction.knowledge_bundle_id ? (
                    <span className={styles.chip}>{selectedAction.knowledge_bundle_id}</span>
                  ) : null}
                  {selectedAction.triggering_rule_ids.map((ruleId) => (
                    <span key={ruleId} className={styles.chip}>
                      {ruleId}
                    </span>
                  ))}
                  {selectedAction.constraints_applied.map((constraint) => (
                    <span key={constraint} className={styles.chip}>
                      {constraint}
                    </span>
                  ))}
                </div>
              </div>

              <div className={styles.detailSection}>
                <p className={styles.label}>Review controls</p>
                <div className={styles.controls}>
                  <button
                    type="button"
                    className={`${styles.reviewButton} ${styles.approve}`}
                    onClick={() => void submitDecision("approve")}
                    disabled={reviewMutation.isPending}
                  >
                    Approve
                  </button>
                  <button
                    type="button"
                    className={`${styles.reviewButton} ${styles.reject}`}
                    onClick={() => void submitDecision("reject")}
                    disabled={reviewMutation.isPending}
                  >
                    Reject
                  </button>
                  <button
                    type="button"
                    className={`${styles.reviewButton} ${styles.escalate}`}
                    onClick={() => void submitDecision("escalate")}
                    disabled={reviewMutation.isPending}
                  >
                    Escalate
                  </button>
                  <button type="button" className={styles.disabledButton} disabled>
                    Defer not yet supported
                  </button>
                  <button
                    type="button"
                    className={styles.traceButton}
                    onClick={() => openTrace(selectedAction.action_id)}
                  >
                    Open trace
                  </button>
                </div>
                <div style={{ marginTop: "14px" }}>
                  <textarea
                    className={styles.notes}
                    value={reviewNotes}
                    onChange={(event) => setReviewNotes(event.target.value)}
                  />
                </div>
                {message ? <div className={styles.message}>{message}</div> : null}
              </div>
            </>
          ) : (
            <div className={styles.detailHeader}>
              <h2>No action selected</h2>
              <p>Select an action from the inbox to inspect its current reasoning and review controls.</p>
            </div>
          )}
        </section>
      </div>
    </section>
  );
}
