import type { EventEnvelope } from "../types/api";

export const demoEvents: EventEnvelope[] = [
  {
    event_type: "patient_location",
    occurred_at: "2026-03-25T10:00:00Z",
    recorded_at: "2026-03-25T10:00:00Z",
    source_system: "demo_emr",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "patient_location",
      patient_id: "patient-1",
      room_id: "room-101",
      ward_id: "ward-a",
    },
  },
  {
    event_type: "room_metadata",
    occurred_at: "2026-03-25T10:05:00Z",
    recorded_at: "2026-03-25T10:05:00Z",
    source_system: "demo_bed_mgmt",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "room_metadata",
      room_id: "room-101",
      ward_id: "ward-a",
      room_type: "double_room",
      capacity: 2,
    },
  },
  {
    event_type: "patient_location",
    occurred_at: "2026-03-30T09:55:00Z",
    recorded_at: "2026-03-30T09:55:00Z",
    source_system: "demo_emr",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "patient_location",
      patient_id: "patient-2",
      room_id: "room-102",
      ward_id: "ward-a",
    },
  },
  {
    event_type: "room_metadata",
    occurred_at: "2026-03-30T09:56:00Z",
    recorded_at: "2026-03-30T09:56:00Z",
    source_system: "demo_bed_mgmt",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "room_metadata",
      room_id: "room-102",
      ward_id: "ward-a",
      room_type: "standard",
      capacity: 1,
    },
  },
  {
    event_type: "suspected_case",
    occurred_at: "2026-03-30T10:00:00Z",
    recorded_at: "2026-03-30T10:00:00Z",
    source_system: "demo_triage",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "suspected_case",
      subject_type: "patient",
      subject_id: "patient-2",
      suspicion_level: "high",
      reason: "Fever, cough, and influenza-like respiratory symptoms at arrival.",
    },
  },
  {
    event_type: "staff_assignment",
    occurred_at: "2026-03-30T10:30:00Z",
    recorded_at: "2026-03-30T10:30:00Z",
    source_system: "demo_emr",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "staff_assignment",
      staff_id: "staff-1",
      ward_id: "ward-a",
      room_id: "room-101",
      role: "nurse",
    },
  },
  {
    event_type: "lab_confirmation",
    occurred_at: "2026-03-30T11:00:00Z",
    recorded_at: "2026-03-30T11:05:00Z",
    source_system: "demo_lab",
    hospital_id: "hospital_ce_001",
    payload: {
      event_type: "lab_confirmation",
      subject_type: "patient",
      subject_id: "patient-1",
      pathogen_code: "influenza",
      result: "positive",
    },
  },
];
